plugins {
    id "com.android.application"
}

if (file("google-services.json").exists()) {
    apply plugin: "com.google.gms.google-services"
}

def uploadKeystorePropertiesFile = rootProject.file("../.local-secrets/upload-keystore.properties")
def uploadKeystoreProperties = new Properties()
if (uploadKeystorePropertiesFile.exists()) {
    uploadKeystoreProperties.load(new FileInputStream(uploadKeystorePropertiesFile))
}

android {
    namespace "one.ortus.storageretschwil"
    compileSdk 35

    defaultConfig {
        applicationId "one.ortus.storageretschwil"
        minSdk 23
        targetSdk 35
        versionCode 6
        versionName "1.0.5"
    }

    signingConfigs {
        release {
            if (uploadKeystorePropertiesFile.exists()) {
                storeFile file(uploadKeystoreProperties["STORE_FILE"])
                storePassword uploadKeystoreProperties["STORE_PASSWORD"]
                keyAlias uploadKeystoreProperties["KEY_ALIAS"]
                keyPassword uploadKeystoreProperties["KEY_PASSWORD"]
            }
        }
    }

    buildTypes {
        release {
            if (uploadKeystorePropertiesFile.exists()) {
                signingConfig signingConfigs.release
            }
        }
    }
}

dependencies {
    implementation "androidx.biometric:biometric:1.1.0"
    implementation "androidx.core:core:1.13.1"
    implementation "androidx.fragment:fragment:1.6.2"
    implementation platform("com.google.firebase:firebase-bom:33.7.0")
    implementation "com.google.firebase:firebase-messaging"
}
